# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regimens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regimen',
            options={'ordering': ['-date_started', '-date_ended']},
        ),
    ]
