# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of this medical report', max_length=100, verbose_name='Title')),
                ('notes', models.TextField(blank=True, help_text='Information on the medical report. This field is optional', null=True, verbose_name='Notes')),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date on which this medical report was created', verbose_name='Date created')),
                ('date_last_modified', models.DateField(auto_now=True, help_text='The date on which the details of this medical report were last modified', verbose_name='Date last modified')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user that created this medical report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_reports', related_query_name='created_medical_report', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user that last modified this medical report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_medical_reports', related_query_name='modified_medical_report', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('patient', models.ForeignKey(help_text='The patient whom this medical report is for', on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', related_query_name='medical_report', to='patients.Patient', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name to give to this medical report type', max_length=100, unique=True, verbose_name='Medical report type name')),
                ('description', models.TextField(blank=True, help_text='The purpose of this medical report type. This field is optional', null=True, verbose_name='Description')),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date on which the medical report type was created', verbose_name='Date created')),
                ('date_last_modified', models.DateField(auto_now=True, help_text='The date on which details of this medical report type were last modified', verbose_name='Date last modified')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user that created this medical report type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_report_types', related_query_name='created_medical_report_type', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user to last modify this medical report type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_medical_report_types', related_query_name='modified_medical_report_type', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='report_type',
            field=models.ForeignKey(help_text='The type of this medical report', on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', related_query_name='medical_report', to='medical.MedicalReportType', verbose_name='Medical report type'),
        ),
    ]
