# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreporttype',
            name='name',
            field=models.CharField(help_text='The name to give to this medical report type', max_length=100, unique=True, verbose_name='Medical report type name'),
        ),
    ]
