# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='Birth Date'),
        ),
    ]
