# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(help_text='The date the adverse event occurred', verbose_name='Event date')),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date the adverse event was added to the system')),
                ('date_last_modified', models.DateField(auto_now=True, help_text='The date that details of this adverse event were last modified')),
            ],
        ),
        migrations.CreateModel(
            name='AdverseEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The unique name for the adverse event type', max_length=100, unique=True, verbose_name='Adverse event type name')),
                ('description', models.TextField(help_text='Information about this adverse event type', verbose_name='Description')),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date the adverse event type was added to the system')),
                ('date_last_modified', models.DateField(auto_now=True, help_text='The most recent date that any information on this adverse event type was last modified')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user that added this adverse event type to the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adverse_event_types', related_query_name='created_adverse_event_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the emergency contact', max_length=100, verbose_name='Name')),
                ('email', models.EmailField(help_text='The email address of the emergency contact', max_length=254, verbose_name='Email')),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date the emergency contact was added to the system')),
                ('date_last_modified', models.DateField(auto_now=True, help_text='The most recent date any of the information on this emergency contact was modified')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user that created the emergency contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_emergency_contacts', related_query_name='created_emergency_contact', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user that made the most recent modification to the information of this emergency contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_emergency_contacts', related_query_name='modified_emergency_contact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adverseeventtype',
            name='emergency_contacts',
            field=models.ManyToManyField(help_text='The emergency contacts that are to receive emails when adverse events of this type are created', related_name='adverse_event_types', related_query_name='adverse_event_type', to='adverse.EmergencyContact', verbose_name='Emergency contacts'),
        ),
        migrations.AddField(
            model_name='adverseeventtype',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user to last modify information on this adverse event type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_adverse_event_types', related_query_name='modified_adverse_event_type', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='adverse_event_type',
            field=models.ForeignKey(help_text='The category of this adverse event', on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', related_query_name='adverse_event', to='adverse.AdverseEventType', verbose_name='Adverse event type'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user that added this adverse event to the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adverse_events', related_query_name='created_adverse_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user that last modified the details of this adverse event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_adverse_events', related_query_name='modified_adverse_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='patient',
            field=models.ForeignKey(help_text='The patient whom the adverse event has occurred to', on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', related_query_name='adverse_event', to='patients.Patient', verbose_name='Patient'),
        ),
    ]
