# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverseevent',
            name='notes',
            field=models.TextField(blank=True, help_text='Any information with regards to this adverse event', null=True, verbose_name='Notes'),
        ),
    ]
