# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0002_adverseevent_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseeventtype',
            name='emergency_contacts',
            field=models.ManyToManyField(blank=True, help_text='The emergency contacts that are to receive emails when adverse events of this type are created', related_name='adverse_event_types', related_query_name='adverse_event_type', to='adverse.EmergencyContact', verbose_name='Emergency contacts'),
        ),
    ]
