# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The unique title for the program', max_length=100, unique=True, verbose_name='Program name')),
                ('description', models.TextField(blank=True, help_text='The purpose of the program. This field is optional', null=True, verbose_name='Description')),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date the program was first saved into the system')),
                ('date_last_modified', models.DateField(auto_now=True, help_text='The most recent date any of the fields of the program was updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user that add this program to the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', related_query_name='created_program', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user that made the most recent update to any of the program fields', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_programs', related_query_name='modified_program', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
