# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
