# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Is this program ongoing or closed?'),
        ),
    ]
