# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
        ('programs', '0004_auto_20160816_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', related_query_name='created_program', to='user.CommuniqueUser'),
        ),
        migrations.AddField(
            model_name='program',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_programs', related_query_name='modified_program', to='user.CommuniqueUser'),
        ),
    ]
