# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20160817_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', related_query_name='created_program', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_programs', related_query_name='modified_program', to=settings.AUTH_USER_MODEL),
        ),
    ]
