# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes on the counselling session. This field is optional.', null=True, verbose_name='Notes')),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date on which the counselling session was created', verbose_name='Date created')),
                ('date_last_modified', models.DateField(auto_now=True, help_text='The date on which the counselling session was last modified', verbose_name='Date last modified')),
            ],
        ),
        migrations.CreateModel(
            name='CounsellingSessionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name to be given to this counselling session type.', max_length=100, unique=True, verbose_name='Counselling session type')),
                ('description', models.TextField(blank=True, help_text='The description of this counselling session type. This field is optional.', null=True, verbose_name='Description')),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date on which the counselling session type was created.', verbose_name='Date created')),
                ('date_last_modified', models.DateField(auto_now=True, help_text='The date on which the counselling session type was last modified', verbose_name='Date last modified')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user that created the counselling session type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_counselling_session_types', related_query_name='created_counselling_session_type', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user to last modify the counselling session type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_counselling_session_types', related_query_name='modified_counselling_session_type', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
        ),
        migrations.AddField(
            model_name='counsellingsession',
            name='counselling_session_type',
            field=models.ForeignKey(help_text='The category which this counselling session falls into', on_delete=django.db.models.deletion.CASCADE, related_name='counselling_sessions', related_query_name='counselling_session', to='counselling_sessions.CounsellingSessionType', verbose_name='Counselling session type'),
        ),
        migrations.AddField(
            model_name='counsellingsession',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user that administered the counselling session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_counselling_sessions', related_query_name='created_counselling_session', to=settings.AUTH_USER_MODEL, verbose_name='Administered by'),
        ),
        migrations.AddField(
            model_name='counsellingsession',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user to last modify the counselling session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_counselling_sessions', related_query_name='modified_counselling_session', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='counsellingsession',
            name='patient',
            field=models.ForeignKey(help_text='The patient for whom the counselling session is for', on_delete=django.db.models.deletion.CASCADE, related_name='counselling_sessions', related_query_name='counselling_session', to='patients.Patient', verbose_name='Patient'),
        ),
    ]
