# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 19:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CR', 'Created'), ('UP', 'Updated'), ('DL', 'Deleted'), ('OP', 'Opened'), ('CL', 'Closed'), ('AC', 'Activated'), ('DE', 'Deactivated')], max_length=2)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('object_name', models.CharField(default='Model', max_length=100)),
                ('object_url', models.CharField(blank=True, max_length=100, null=True)),
                ('object_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='CommuniqueUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='useractivity',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', related_query_name='user_activity', to=settings.AUTH_USER_MODEL),
        ),
    ]
