# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('AD', 'Admissions'), ('AE', 'Adverse Events'), ('AP', 'Appointments'), ('CS', 'Counselling Sessions'), ('MR', 'Medical Reports'), ('EV', 'Events'), ('PA', 'Patients'), ('PO', 'Patient Outcomes'), ('EN', 'Enrollments'), ('PR', 'Programs'), ('RE', 'Regimens')], help_text='The system service for which to receive notifications', max_length=2, verbose_name='Service')),
                ('user', models.ForeignKey(help_text='The user whom this notification registration is for', on_delete=django.db.models.deletion.CASCADE, related_name='notification_registrations', related_query_name='notification_registration', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
