# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CR', 'Created'), ('UP', 'Updated'), ('DL', 'Deleted'), ('OP', 'Opened'), ('CL', 'Closed'), ('AC', 'Activated'), ('DE', 'Deactivated')], max_length=2)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('object', models.TextField()),
                ('object_url', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', related_query_name='user_activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
