# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20160817_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='object',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='object_name',
            field=models.CharField(default='Model', max_length=100),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='object_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
