# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20160817_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='object_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
