# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="The patient's first name. This field is required.", max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(help_text="The patient's last name. This field is required.", max_length=100, verbose_name='Last name')),
                ('middle_name', models.CharField(blank=True, help_text="The patient's middle name. This field is optional.", max_length=100, null=True, verbose_name='Middle name')),
                ('birth_date', models.DateField(blank=True, help_text='Please use the following format: DD/MM/YYYY. This field is optional.', null=True, verbose_name='Birth Date')),
                ('identifier', models.CharField(blank=True, help_text='The identifier used in the existing filing system. This field is optional.', max_length=150, null=True, unique=True, verbose_name='Patient Identifier')),
                ('location', models.CharField(blank=True, help_text='The current residential address of the patient. This field is optional.', max_length=150, null=True, verbose_name='Patient location')),
                ('contact_number', models.CharField(blank=True, help_text='The telephone/mobile number for the patient. This field is optional.', max_length=50, null=True, verbose_name='Contact number')),
                ('reference_health_centre', models.CharField(blank=True, help_text='The health centre to be contacted for more information. This field is optional.', max_length=150, null=True, verbose_name='Reference health centre')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date/time the patient was created.')),
                ('date_last_modified', models.DateTimeField(auto_now=True, help_text="The last date/time the patient's information was modified.")),
                ('created_by', models.ForeignKey(blank=True, help_text='The user that created the patient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', related_query_name='created_patient', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text="The last user to modify the patient's information.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_patients', related_query_name='modified_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
