# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True, help_text='The date the patient was enrolled into the program.', verbose_name='date of enrollment')),
                ('comment', models.TextField(help_text='A comment on the enrollment', verbose_name='comment')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this enrollment is still active.', verbose_name='is open')),
                ('enrolled_by', models.ForeignKey(blank=True, help_text="The user that registers a patient's enrollment into a program.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_enrollments', related_query_name='registered_enrollment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text="The patient's last name", max_length=100, verbose_name='Last name')),
                ('other_names', models.CharField(help_text='The middle and first names of the patient', max_length=150, verbose_name='Names')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='The sex of the patient', max_length=1, verbose_name="Patient's sex")),
                ('birth_date', models.DateField(blank=True, help_text='Please use the following format: DD/MM/YYYY. This field is optional.', null=True, verbose_name='Birth Date')),
                ('identifier', models.CharField(blank=True, help_text='The identifier used in the existing filing system', max_length=150, null=True, unique=True, verbose_name='Patient Identifier')),
                ('location', models.CharField(blank=True, help_text='The current residential address of the patient. This field is optional.', max_length=150, null=True, verbose_name="Patient's address")),
                ('contact_number', models.CharField(blank=True, help_text='The telephone/mobile number for the patient. This field is optional.', max_length=50, null=True, verbose_name='Contact number')),
                ('reference_health_centre', models.CharField(blank=True, help_text='The health centre to be contacted for more information. This field is optional.', max_length=150, null=True, verbose_name='Reference health centre')),
                ('interim_outcome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Interim outcome')),
                ('treatment_start_date', models.DateField(blank=True, help_text='The date the patient started treatment', null=True, verbose_name='Treatment start date')),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date/time the patient was created.')),
                ('date_last_modified', models.DateField(auto_now=True, help_text="The last date/time the patient's information was modified.")),
                ('created_by', models.ForeignKey(blank=True, help_text='The user that created the patient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', related_query_name='created_patient', to=settings.AUTH_USER_MODEL)),
                ('enrolled_programs', models.ManyToManyField(related_name='enrolled_patients', related_query_name='enrolled_patient', through='patients.Enrollment', to='programs.Program')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text="The last user to modify the patient's information.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_patients', related_query_name='modified_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='patient',
            field=models.ForeignKey(help_text='The patient enrolled in the program.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', related_query_name='enrollment', to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='program',
            field=models.ForeignKey(help_text='The program to which a patient is enrolled', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', related_query_name='enrollment', to='programs.Program'),
        ),
    ]
