# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateField(help_text='The date the patient was enrolled into the program.', verbose_name='Enrollment date'),
        ),
    ]
